- params:
    git:
      repoName: pipyexample
      branches:
        - main
    # scan:
    #   projects:
    #     - repository: cdaas-python-vr
    #       workingDirs:
    #         - /
    #     - repository: cdaas-npm-vr
    #       workingDirs:
    #         - /
